#!/usr/bin/env Rscript

# Step 07: Pairwise sample correlation analysis
#
# This script calculates pairwise Pearson correlation matrices
# based on IGHV and VJ usage frequency matrices generated by Step 06.
#
# Input:
#   results/06_ighv_vj_usage/IGHV_V3J_weight_matrix.tsv
#   results/06_ighv_vj_usage/IGHV_reads_weight_matrix.tsv
#   results/06_ighv_vj_usage/VJ_V3J_weight_matrix.tsv
#   results/06_ighv_vj_usage/VJ_reads_weight_matrix.tsv
#
# Output:
#   results/07_repertoire_correlation/*_correlation_matrix.tsv

args <- commandArgs(trailingOnly = TRUE)

usage_dir <- ifelse(length(args) >= 1, args[1], "results/06_ighv_vj_usage")
out_dir   <- ifelse(length(args) >= 2, args[2], "results/07_repertoire_correlation")

dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# ------------------------------------------------------------
# Function: calculate pairwise correlation matrix
# ------------------------------------------------------------

calculate_correlation <- function(input_file, feature_col, output_file) {
  if (!file.exists(input_file)) {
    stop("Input file not found: ", input_file)
  }

  usage_matrix <- read.table(
    file = input_file,
    header = TRUE,
    sep = "\t",
    stringsAsFactors = FALSE,
    check.names = FALSE,
    quote = "",
    comment.char = ""
  )

  if (!feature_col %in% colnames(usage_matrix)) {
    stop(
      "Feature column '", feature_col, "' not found in ",
      input_file,
      ". Available columns are: ",
      paste(colnames(usage_matrix), collapse = ", ")
    )
  }

  sample_matrix <- usage_matrix[, colnames(usage_matrix) != feature_col, drop = FALSE]

  # Convert all sample columns to numeric.
  sample_matrix[] <- lapply(sample_matrix, function(x) {
    as.numeric(as.character(x))
  })

  # Remove features with missing values across all samples, if any.
  keep_rows <- rowSums(!is.na(sample_matrix)) > 0
  sample_matrix <- sample_matrix[keep_rows, , drop = FALSE]

  # Calculate Pearson correlation between samples.
  cor_matrix <- cor(
    sample_matrix,
    method = "pearson",
    use = "pairwise.complete.obs"
  )

  cor_matrix <- as.data.frame(cor_matrix)
  cor_matrix <- cbind(sample_id = rownames(cor_matrix), cor_matrix)

  write.table(
    cor_matrix,
    file = output_file,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  message("Correlation matrix written to: ", output_file)
}

# ------------------------------------------------------------
# Input and output files
# ------------------------------------------------------------

IGHV_V3J_file <- file.path(usage_dir, "IGHV_V3J_weight_matrix.tsv")
IGHV_reads_file <- file.path(usage_dir, "IGHV_reads_weight_matrix.tsv")
VJ_V3J_file <- file.path(usage_dir, "VJ_V3J_weight_matrix.tsv")
VJ_reads_file <- file.path(usage_dir, "VJ_reads_weight_matrix.tsv")

# ------------------------------------------------------------
# Run correlation analysis
# ------------------------------------------------------------

calculate_correlation(
  input_file = IGHV_V3J_file,
  feature_col = "V_segment",
  output_file = file.path(out_dir, "IGHV_V3J_weight_correlation_matrix.tsv")
)

calculate_correlation(
  input_file = IGHV_reads_file,
  feature_col = "V_segment",
  output_file = file.path(out_dir, "IGHV_reads_weight_correlation_matrix.tsv")
)

calculate_correlation(
  input_file = VJ_V3J_file,
  feature_col = "VJ_combination",
  output_file = file.path(out_dir, "VJ_V3J_weight_correlation_matrix.tsv")
)

calculate_correlation(
  input_file = VJ_reads_file,
  feature_col = "VJ_combination",
  output_file = file.path(out_dir, "VJ_reads_weight_correlation_matrix.tsv")
)

message("Step 07 finished: pairwise correlation analysis completed.")
message("Output directory: ", out_dir)
